title: "Isaac Manring"
description: >-
  A personal website for sharing research and technical blog posts.
url: "https://imanring.github.io"
baseurl: ""

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _figures

markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - blog.md
  - about.md

permalink: /blog/:year/:month/:day/:title/

exclude:
  - README.md
  - Gemfile.lock

